Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,28 +1,22 @@
 pipeline {
     agent any
     tools {
-        nodejs 'NODEJS_20'
+        nodejs 'nodejs-20.11.0'=
     }
 
     environment {
         NODEJS_HOME = 'C:/Program Files/nodejs'
-        SONAR_SCANNER_PATH = 'D:/Worldline Classes/sonar-scanner-6.2.1.4610-windows-x64/bin'
+        SONAR_SCANNER_PATH = 'C:/Users/ADMIN/Downloads/sonar-scanner-cli-6.2.1.4610-windows-x64/sonar-scanner-6.2.1.4610-windows-x64/bin'
     }
 
     stages {
         stage('Checkout') {
             steps {
-                git branch: 'main', url: 'https://github.com/HemantModi11/SonarQube-Assignment.git'
+                checkout scm
             }
         }
 
-        stage('Clone Repository') {
-            steps {
-                git 'https://github.com/HemantModi11/SonarQube-Assignment.git'
-            }
-        }
-
-        stage('Install Dependencies') {
+        stage('Install Backend Dependencies') {
             steps {
                 bat '''
                 set PATH=%NODEJS_HOME%;%PATH%
@@ -31,16 +25,26 @@ pipeline {
             }
         }
 
-        stage('Run SonarQube Analysis') {
+        stage('Backend - Lint') {
+            steps {
+                bat '''
+                set PATH=%NODEJS_HOME%;%PATH%
+                npm run lint
+                '''
+            }
+        }
+
+        stage('SonarQube Analysis') {
             environment {
-                SONAR_TOKEN = credentials('assignment2-token') // Replace with your SonarQube token credential ID
+                SONAR_TOKEN = credentials('assignment2-token')
             }
             steps {
                 bat '''
                 set PATH=%SONAR_SCANNER_PATH%;%PATH%
-                sonar-scanner -Dsonar.projectKey=Assignment-2 ^ 
-                    -Dsonar.sources=. ^ 
-                    -Dsonar.host.url=http://192.168.29.98:9000 ^ 
+                where sonar-scanner || echo "SonarQube scanner not found. Please install it."
+                sonar-scanner -Dsonar.projectKey=Assignment-2 ^
+                    -Dsonar.sources=. ^
+                    -Dsonar.host.url=http://localhost:9000 ^
                     -Dsonar.token=%SONAR_TOKEN% 2>&1
                 '''
             }
@@ -49,13 +53,13 @@ pipeline {
 
     post {
         success {
-            echo 'Pipeline completed successfully.'
+            echo 'Pipeline completed successfully'
         }
         failure {
-            echo 'Pipeline failed. Check logs for details.'
+            echo 'Pipeline failed'
         }
         always {
-            echo 'Pipeline execution finished.'
+            echo 'This runs regardless of the result.'
         }
     }
 }
